set(TARGET llama-embedding-cli)
add_executable(${TARGET} embedding.cpp)
install(TARGETS ${TARGET} RUNTIME)
target_link_libraries(${TARGET} PRIVATE common llama ${CMAKE_THREAD_LIBS_INIT})
target_compile_features(${TARGET} PRIVATE cxx_std_17)

if (BUILD_SHARED_LIBS)
    add_library(llama-embedding embedding.cpp embedding.h)
    install(TARGETS llama-embedding RUNTIME)
    target_link_libraries(llama-embedding PRIVATE common llama ${CMAKE_THREAD_LIBS_INIT})
    target_compile_features(llama-embedding PRIVATE cxx_std_17)
    set_target_properties(llama-embedding PROPERTIES POSITION_INDEPENDENT_CODE ON)
    target_compile_definitions(llama-embedding PRIVATE LLAMA_EMBEDDING_SHARED)
    target_compile_definitions(llama-embedding PRIVATE LLAMA_BUILD)
endif()
